### PR TITLE
Fix specs, changelog and readme after sendgrid v5 merge

### PR DESCRIPTION
**Pull request by tyrauber**
- fixes specs
- updates changelog and readme
- fix deliver! compatibility

### CODE REVIEW

**Comment by tyrauber** [comment]
@eddiezane, this PR addresses the spec failures, readme and changelog changes after the sendgrid v5 PR merge. Note that the sendgrid-ruby gem now requires ruby 2.2 so I updated the travis config accordingly.  I am going to go ahead and merge this in to get master green.  The last PR already version bumped to 2.0.0.  I think we should consider tagging as v2 and pushing a build to rubygems.

**Comment by eddiezane** [comment]
@tyrauber nice work on this!

What's your RubyGems account? I'll get you added there as well so you can cut releases.

**Comment by tyrauber** [comment]
Happy to help. Same as my github handle, tyrauber.

**Comment by eddiezane** [comment]
@tyrauber added!

**Pull request merged**
