### PR TITLE
Fix warnings with ruby 2.7

### PR DESCRIPTION
**Pull request by jfabre**
Please let me know if I need to change anything.

### CODE REVIEW

**Comment by tyrauber** [comment]
@jfabre Thanks for this! What do you think about adding some 2.7 test coverage by updating the rvm list of the [.travis.yml](https://github.com/eddiezane/sendgrid-actionmailer/blob/master/.travis.yml)?

**Comment by tyrauber** [comment]
Merged and bumped to 3.1.0.

**Comment by jfabre** [comment]
Hey I'm sorry, I must have forgotten about your reply.

Thanks for merging it anyway.

**Comment by tyrauber** [comment]
Hey, no worries, @jfabre, I appreciate the pull request.  I added the 2.7.1 coverage. We're good to go.

**Pull request merged**
