### PR TITLE
Remove memoization of client

### PR DESCRIPTION
**Pull request by michaeldever**
Remove memoization of SendGrid client, allowing for dynamic API keys.

### CODE REVIEW

**Comment by tyrauber** [comment]
@michaeldever Thanks for this. What do you think about restructuring this functionality a little bit, like in #34?

**Comment by michaeldever** [comment]
@tyrauber Looks good, just a small suggestion to keep the api_key logic to one function.

**Comment by tyrauber** [comment]
Yep, received and updated. Thanks a ton for the pull request and review.  Most appreciated!

**Comment by tyrauber** [comment]
Addressed in #34. Thanks for all the help.

**Pull request closed without merging**
