### PR TITLE
Respect actionmailer delivery_method_options for api_key

### PR DESCRIPTION
**Pull request by michaeldever**
This PR includes the ability to dynamically set the SendGrid API key so that the mailer can be used across multiple objects that have a sendgrid API key.

### CODE REVIEW

**Comment by tyrauber** [comment]
Hi @michaeldever Thanks for the pull request!  Quick question:  Won't the caching of @client on [line 58](https://github.com/eddiezane/sendgrid-actionmailer/pull/32/files#diff-5f8621c144b574135a554c09fcdc5a0bR58) pose a problem to switching between api keys?

**Comment by michaeldever** [comment]
Hey @tyrauber, yeah, I thought of this too, but it didn't seem to have any effects during my testing. Very happy to remove that memorization either way as there isn't any apparent performance impact.

**Comment by tyrauber** [comment]
@michaeldever, Real keys in a live environment?  Regardless, if there is no apparent performance impact, removing the memoization is certainly the safest bet.

**Comment by michaeldever** [comment]
@tyrauber, aye, tested with live keys earlier. Will throw up a commit removing the memorization tomorrow morning.

**Pull request merged**
